# Generated by Django 4.1 on 2022-08-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contacts',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
