# Generated by Django 4.1 on 2022-08-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_contacts_client_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firstname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
