# Generated by Django 4.1 on 2022-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_firstname_client_last_name_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contacts',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
