# Generated by Django 4.1 on 2022-08-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='address',
        ),
        migrations.AddField(
            model_name='bottle',
            name='oreders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='clients.order', verbose_name='Заказы'),
        ),
    ]
