# Generated by Django 4.1 on 2022-08-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_bottle_address_bottle_oreders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='oreders',
            new_name='orders',
        ),
    ]
